export const temperaturesStates = {
  "Clouds": "/assets/images/cloudy.png",
  "Clear": "/assets/images/sun.png",
  "Rain": "/assets/images/rain.png",
  "Snow": "snowy",
  "Thunderstorm": "stormy",
  "Drizzle": "rainy",
  "Mist": "cloudy",
  "Smoke": "cloudy",
  "Haze": "cloudy",
  "Dust": "cloudy",
  "Fog": "cloudy",
  "Sand": "cloudy",
  "Ash": "cloudy",
  "Squall": "cloudy",
  "Tornado": "cloudy",
}
export const temperaturesStates2 = {
  "cloudy": "/assets/images/cloudy.png",
  "clear-day": "/assets/images/sun.png",
  "rain": "/assets/images/rain.png",
  "partly-cloudy-day":"/assets/images/partly-cloudy.png",
  "Snow": "snowy",
  "Thunderstorm": "stormy",
  "Drizzle": "rainy",
  "Mist": "cloudy",
  "Smoke": "cloudy",
  "Haze": "cloudy",
  "Dust": "cloudy",
  "Fog": "cloudy",
  "Sand": "cloudy",
  "Ash": "cloudy",
  "Squall": "cloudy",
  "Tornado": "cloudy",
}